//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheFinalSalesProject.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Skin_Name {
            get {
                return ((string)(this["Skin_Name"]));
            }
            set {
                this["Skin_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Skin_Plate {
            get {
                return ((string)(this["Skin_Plate"]));
            }
            set {
                this["Skin_Plate"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source = .\\NOURADDIN;Initial Catalog = FinalSalesDB;Integrated Security = tr" +
            "ue ;")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PFO935N\\NOURADDIN;Initial Catalog=FinalSalesDB;Integrated Sec" +
            "urity=True")]
        public string FinalSalesDBConnectionString {
            get {
                return ((string)(this["FinalSalesDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Read_From_Scale_Barcode {
            get {
                return ((bool)(this["Read_From_Scale_Barcode"]));
            }
            set {
                this["Read_From_Scale_Barcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string Scale_Barcode_PreFix {
            get {
                return ((string)(this["Scale_Barcode_PreFix"]));
            }
            set {
                this["Scale_Barcode_PreFix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte Product_Code_Length {
            get {
                return ((byte)(this["Product_Code_Length"]));
            }
            set {
                this["Product_Code_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public byte BarCode_Length {
            get {
                return ((byte)(this["BarCode_Length"]));
            }
            set {
                this["BarCode_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public byte Value_Code_Length {
            get {
                return ((byte)(this["Value_Code_Length"]));
            }
            set {
                this["Value_Code_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte Read_Mode {
            get {
                return ((byte)(this["Read_Mode"]));
            }
            set {
                this["Read_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ignore_Check_Digit {
            get {
                return ((bool)(this["Ignore_Check_Digit"]));
            }
            set {
                this["Ignore_Check_Digit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte Divide_Value_By {
            get {
                return ((byte)(this["Divide_Value_By"]));
            }
            set {
                this["Divide_Value_By"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte PrintMode {
            get {
                return ((byte)(this["PrintMode"]));
            }
            set {
                this["PrintMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62")]
        public int Discount_Allowed_Accoun_ID {
            get {
                return ((int)(this["Discount_Allowed_Accoun_ID"]));
            }
            set {
                this["Discount_Allowed_Accoun_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public int Discount_Received_Account_ID {
            get {
                return ((int)(this["Discount_Received_Account_ID"]));
            }
            set {
                this["Discount_Received_Account_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("66")]
        public int Sales_Tax_Account_ID {
            get {
                return ((int)(this["Sales_Tax_Account_ID"]));
            }
            set {
                this["Sales_Tax_Account_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("67")]
        public int Buy_Tax_Account_ID {
            get {
                return ((int)(this["Buy_Tax_Account_ID"]));
            }
            set {
                this["Buy_Tax_Account_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("68")]
        public int Buy_Expenese_Account_ID {
            get {
                return ((int)(this["Buy_Expenese_Account_ID"]));
            }
            set {
                this["Buy_Expenese_Account_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sylfaen")]
        public string Font_Name {
            get {
                return ((string)(this["Font_Name"]));
            }
            set {
                this["Font_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public float Font_Size {
            get {
                return ((float)(this["Font_Size"]));
            }
            set {
                this["Font_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Is_Bold {
            get {
                return ((bool)(this["Is_Bold"]));
            }
            set {
                this["Is_Bold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Is_Italic {
            get {
                return ((bool)(this["Is_Italic"]));
            }
            set {
                this["Is_Italic"] = value;
            }
        }
    }
}
